site_name: Blog
site_url: https://pykampala-community.github.io
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: black
plugins:
  - blog:
      blog_dir: .
      categories: true
      categories_allowed:
        - Tutorial
        - Benchmark
        - Performance
        - Data
        - Ai
        - Project
        - General