authors:
  Toebias-HT:
    name: "Toe•bias"
    description: "Pythonista, VM and CPU design enthusiast, working on a new programming language."
    avatar: https://avatars.githubusercontent.com/u/35004147?s=400&u=a6d3e4ead9606eb6cc15bdd65e4b1c9c13ded869&v=4